---
- name: Install apt prerequsites
  apt: name={{ item }} update_cache=yes
  with_items: ["git", "python-pip"]
  
- name: Intall pip requirements
  pip: name={{ item }}
  with_items:
    - requests
    
- name: Clone the PyTasc repository
  git:
    repo:     "https://github.com/hcpss-banderson/py-tasc.git"
    version:  "{{ pytasc_version }}"
    dest:     "{{ pytasc_destination }}"
