---
- name: Find out if git is installed
  command: dpkg -s git
  register: git_check

- name: Install prerequsites
  apt: name=git update_cache=yes
  when: git_check.rc == 1
    
- name: Clone the PyTasc repository
  git:
    repo:     "https://github.com/hcpss-banderson/py-tasc.git"
    version:  "{{ pytasc_version }}"
    dest:     "{{ pytasc_destination }}"
